import re
from typing import Dict, Set

# ══════════════════════════════════════════════════════════
# 1. LOOKUP MAPS
# ══════════════════════════════════════════════════════════

COUNTRY_MAP: Dict[str, str] = {
    "AFGHANISTAN": "AF", "ALBANIA": "AL", "ALGERIA": "DZ", "AMERICAN SAMOA": "AS", "ANDORRA": "AD", "ANGOLA": "AO", "ANGUILLA": "AI",
    "ANTARCTICA": "AQ", "ANTARCTICA (THE TERRITORY SOUTH OF 60 DEG S)": "AQ", "ANTIGUA AND BARBUDA": "AG", "ARGENTINA": "AR", "ARMENIA": "AM",
    "ARUBA": "AW", "AUSTRALIA": "AU", "AUSTRIA": "AT", "AZERBAIJAN": "AZ", "BAHAMAS": "BS", "BAHRAIN": "BH", "BANGLADESH": "BD",
    "BARBADOS": "BB", "BELARUS": "BY", "BELGIUM": "BE", "BELIZE": "BZ", "BENIN": "BJ", "BERMUDA": "BM", "BHUTAN": "BT",
    "BILLING_COUNTRY": "IN", "BOLIVIA": "BO", "BOSNIA AND HERZEGOVINA": "BA", "BOTSWANA": "BW", "BOUVET ISLAND (BOUVETOYA)": "BV",
    "BRAZIL": "BR", "BRITISH VIRGIN ISLANDS": "VG", "BRUNEI DARUSSALAM": "BN", "BULGARIA": "BG", "BURKINA FASO": "BF", "BURUNDI": "BI",
    "CAMBODIA": "KH", "CAMEROON": "CM", "CANADA": "CA", "CAPE VERDE": "CV", "CAYMAN ISLANDS": "KY", "CENTRAL AFRICAN REPUBLIC": "CF",
    "CHAD": "TD", "CHILE": "CL", "CHINA": "CN", "COCOS (KEELING) ISLANDS": "CC", "COLOMBIA": "CO", "COMOROS": "KM", "CONGO": "CG",
    "COOK ISLANDS": "CK", "COSTA RICA": "CR", "CROATIA": "HR", "CUBA": "CU", "CYPRUS": "CY", "CZECH REPUBLIC": "CZ", "DENMARK": "DK",
    "DJIBOUTI": "DJ", "DOMINICA": "DM", "DOMINICAN REPUBLIC": "DO", "ECUADOR": "EC", "EGYPT": "EG", "EL SALVADOR": "SV",
    "EQUATORIAL GUINEA": "GQ", "ERITREA": "ER", "ESTONIA": "EE", "ETHIOPIA": "ET", "FALKLAND ISLANDS (MALVINAS)": "FK", "FAROE ISLANDS": "FO",
    "FIJI": "FJ", "FINLAND": "FI", "FRANCE": "FR", "FRENCH GUIANA": "GF", "FRENCH POLYNESIA": "PF", "FRENCH SOUTHERN TERRITORIES": "TF",
    "GABON": "GA", "GAMBIA": "GM", "GEORGIA": "GE", "GERMANY": "DE", "GHANA": "GH", "GIBRALTAR": "GI", "GREECE": "GR", "GREENLAND": "GL",
    "GRENADA": "GD", "GUADELOUPE": "GP", "GUAM": "GU", "GUATEMALA": "GT", "GUERNSEY": "GG", "GUINEA": "GN", "GUINEA-BISSAU": "GW",
    "GUYANA": "GY", "HAITI": "HT", "HEARD ISLAND AND MCDONALD ISLANDS": "HM", "HOLY SEE (VATICAN CITY STATE)": "VA", "HONDURAS": "HN",
    "HONG KONG": "HK", "HUNGARY": "HU", "ICELAND": "IS", "INDIA": "IN", "INDONESIA": "ID", "IRAN": "IR", "IRAQ": "IQ", "IRELAND": "IE",
    "ISLE OF MAN": "IM", "ISRAEL": "IL", "ITALY": "IT", "JAMAICA": "JM", "JAPAN": "JP", "JERSEY": "JE", "JORDAN": "JO", "KAZAKHSTAN": "KZ",
    "KENYA": "KE", "KIRIBATI": "KI", "KOREA": "KR", "SOUTH KOREA": "KR", "NORTH KOREA": "KP", "KUWAIT": "KW", "KYRGYZ REPUBLIC": "KG",
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC": "LA", "LATVIA": "LV", "LEBANON": "LB", "LESOTHO": "LS", "LIBERIA": "LR", "LIBYA": "LY",
    "LIECHTENSTEIN": "LI", "LITHUANIA": "LT", "LUXEMBOURG": "LU", "MACAO": "MO", "MACAU": "MO", "MADAGASCAR": "MG", "MALAWI": "MW",
    "MALAYSIA": "MY", "MALDIVES": "MV", "MALI": "ML", "MALTA": "MT", "MARSHALL ISLANDS": "MH", "MARTINIQUE": "MQ", "MAURITANIA": "MR",
    "MAURITIUS": "MU", "MEXICO": "MX", "MICRONESIA": "FM", "MOLDOVA": "MD", "MONACO": "MC", "MONGOLIA": "MN", "MONTSERRAT": "MS",
    "MOROCCO": "MA", "MOZAMBIQUE": "MZ", "MYANMAR": "MM", "NAMIBIA": "NA", "NAURU": "NR", "NEPAL": "NP", "NETHERLANDS": "NL",
    "NETHERLANDS ANTILLES": "AN", "NEW CALEDONIA": "NC", "NEW ZEALAND": "NZ", "NICARAGUA": "NI", "NIGER": "NE", "NIGERIA": "NG",
    "NIUE": "NU", "NORFOLK ISLAND": "NF", "NORWAY": "NO", "OMAN": "OM", "PAKISTAN": "PK", "PALAU": "PW", "PALESTINIAN TERRITORY": "PS",
    "PANAMA": "PA", "PAPUA NEW GUINEA": "PG", "PARAGUAY": "PY", "PERU": "PE", "PHILIPPINES": "PH", "POLAND": "PL", "PORTUGAL": "PT",
    "PUERTO RICO": "PR", "QATAR": "QA", "ROMANIA": "RO", "RUSSIA": "RU", "RUSSIAN FEDERATION": "RU", "RWANDA": "RW", "SAINT BARTHELEMY": "BL",
    "SAINT HELENA": "SH", "SAINT KITTS AND NEVIS": "KN", "SAINT LUCIA": "LC", "SAINT MARTIN": "MF", "SAINT PIERRE AND MIQUELON": "PM",
    "SAINT VINCENT AND THE GRENADINES": "VC", "SAMOA": "WS", "SAN MARINO": "SM", "SAO TOME AND PRINCIPE": "ST", "SAUDI ARABIA": "SA",
    "SENEGAL": "SN", "SERBIA": "RS", "SEYCHELLES": "SC", "SIERRA LEONE": "SL", "SINGAPORE": "SG", "SLOVAKIA (SLOVAK REPUBLIC)": "SK",
    "SLOVENIA": "SI", "SOLOMON ISLANDS": "SB", "SOMALIA": "SO", "SOUTH AFRICA": "ZA", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS": "GS",
    "SPAIN": "ES", "SRI LANKA": "LK", "SUDAN": "SD", "SURINAME": "SR", "SVALBARD & JAN MAYEN ISLANDS": "SJ", "SWAZILAND": "SZ",
    "ESWATINI": "SZ", "SWEDEN": "SE", "SWITZERLAND": "CH", "SYRIAN ARAB REPUBLIC": "SY", "TAIWAN": "TW", "TAJIKISTAN": "TJ",
    "TANZANIA": "TZ", "THAILAND": "TH", "TIMOR-LESTE": "TL", "TOGO": "TG", "TOKELAU": "TK", "TONGA": "TO", "TRINIDAD AND TOBAGO": "TT",
    "TUNISIA": "TN", "TURKEY": "TR", "TURKMENISTAN": "TM", "TURKS AND CAICOS ISLANDS": "TC", "TUVALU": "TV", "UAE": "AE", "UGANDA": "UG",
    "UK": "GB", "UKRAINE": "UA", "UNITED ARAB EMIRATES": "AE", "UNITED KINGDOM": "GB", "UNITED STATES": "US",
    "UNITED STATES MINOR OUTLYING ISLANDS": "UM", "UNITED STATES OF AMERICA": "US", "UNITED STATES VIRGIN ISLANDS": "VI", "URUGUAY": "UY",
    "USA": "US", "UZBEKISTAN": "UZ", "VANUATU": "VU", "VENEZUELA": "VE", "VIETNAM": "VN", "VIRGIN ISLANDS (BRITISH)": "VG",
    "VIRGIN ISLANDS (U.S.)": "VI", "WESTERN SAHARA": "EH", "YEMEN": "YE", "ZAMBIA": "ZM", "ZIMBABWE": "ZW",
    "IN": "IN", "US": "US", "DE": "DE", "FR": "FR", "GB": "GB", "CA": "CA", "AU": "AU", "JP": "JP", "CN": "CN", "IT": "IT", "BR": "BR", "RU": "RU", "MX": "MX", "ES": "ES", "NL": "NL", "CH": "CH", "SE": "SE", "SG": "SG", "AE": "AE", "KR": "KR"
}

COUNTRY_MAP_3: Dict[str, str] = {
    "AFGHANISTAN": "AFG", "ALBANIA": "ALB", "ALGERIA": "DZA", "AMERICAN SAMOA": "ASM", "ANDORRA": "AND", "ANGOLA": "AGO",
    "ARGENTINA": "ARG", "ARMENIA": "ARM", "ARUBA": "ABW", "AUSTRALIA": "AUS", "AUSTRIA": "AUT", "AZERBAIJAN": "AZE",
    "BAHAMAS": "BHS", "BAHRAIN": "BHR", "BANGLADESH": "BGD", "BARBADOS": "BRB", "BELARUS": "BLR", "BELGIUM": "BEL",
    "BERMUDA": "BMU", "BHUTAN": "BTN", "BOLIVIA": "BOL", "BRAZIL": "BRA", "BULGARIA": "BGR", "CAMBODIA": "KHM",
    "CANADA": "CAN", "CHILE": "CHL", "CHINA": "CHN", "COLOMBIA": "COL", "COSTA RICA": "CRI", "CROATIA": "HRV",
    "CUBA": "CUB", "CYPRUS": "CYP", "CZECH REPUBLIC": "CZE", "DENMARK": "DNK", "EGYPT": "EGY", "ESTONIA": "EST",
    "FINLAND": "FIN", "FRANCE": "FRA", "GERMANY": "DEU", "GHANA": "GHA", "GREECE": "GRC", "HONG KONG": "HKG",
    "HUNGARY": "HUN", "ICELAND": "ISL", "INDIA": "IND", "INDONESIA": "IDN", "IRAN": "IRN", "IRAQ": "IRQ",
    "IRELAND": "IRL", "ISRAEL": "ISR", "ITALY": "ITA", "JAMAICA": "JAM", "JAPAN": "JPN", "JORDAN": "JOR",
    "KAZAKHSTAN": "KAZ", "KENYA": "KEN", "KOREA": "KOR", "SOUTH KOREA": "KOR", "KUWAIT": "KWT", "LATVIA": "LVA",
    "LEBANON": "LBN", "LIBYA": "LBY", "LITHUANIA": "LTU", "LUXEMBOURG": "LUX", "MALAYSIA": "MYS", "MALDIVES": "MDV",
    "MALTA": "MLT", "MEXICO": "MEX", "MONACO": "MCO", "MONGOLIA": "MNG", "MOROCCO": "MAR", "NEPAL": "NPL",
    "NETHERLANDS": "NLD", "NEW ZEALAND": "NZL", "NIGERIA": "NGA", "NORWAY": "NOR", "OMAN": "OMN", "PAKISTAN": "PAK",
    "PANAMA": "PAN", "PARAGUAY": "PRY", "PERU": "PER", "PHILIPPINES": "PHL", "POLAND": "POL", "PORTUGAL": "PRT",
    "QATAR": "QAT", "ROMANIA": "ROU", "RUSSIA": "RUS", "RUSSIAN FEDERATION": "RUS", "SAUDI ARABIA": "SAU",
    "SINGAPORE": "SGP", "SLOVAKIA": "SVK", "SLOVENIA": "SVN", "SOUTH AFRICA": "ZAF", "SPAIN": "ESP", "SRI LANKA": "LKA",
    "SUDAN": "SDN", "SWEDEN": "SWE", "SWITZERLAND": "CHE", "TAIWAN": "TWN", "THAILAND": "THA", "TUNISIA": "TUN",
    "TURKEY": "TUR", "UAE": "ARE", "UNITED ARAB EMIRATES": "ARE", "UNITED KINGDOM": "GBR", "UK": "GBR",
    "UNITED STATES": "USA", "UNITED STATES OF AMERICA": "USA", "USA": "USA", "URUGUAY": "URY", "VENEZUELA": "VEN",
    "VIETNAM": "VNM", "ZIMBABWE": "ZWE",
    "IN": "IND", "US": "USA", "DE": "DEU", "FR": "FRA", "GB": "GBR", "CA": "CAN", "AU": "AUS", "JP": "JPN", "CN": "CHN", "IT": "ITA", "BR": "BRA", "RU": "RUS", "MX": "MEX", "ES": "ESP", "NL": "NLD", "CH": "CHE", "SE": "SWE", "SG": "SGP", "AE": "ARE", "KR": "KOR"
}

CURRENCY_MAP: Dict[str, str] = {
    "INDIAN RUPEE": "INR", "RUPEE": "INR", "RUPEES": "INR", "RS": "INR", "INR": "INR",
    "US DOLLAR": "USD", "DOLLAR": "USD", "USD": "USD",
    "EUROS": "EUR", "EURO": "EUR", "EUR": "EUR",
    "POUND": "GBP", "STERLING": "GBP", "GBP": "GBP",
    "YEN": "JPY", "JPY": "JPY",
    "YUAN": "CNY", "RMB": "CNY", "CNY": "CNY",
    "DIRHAM": "AED", "AED": "AED",
    "RIYAL": "SAR", "SAR": "SAR",
    "FRANC": "CHF", "CHF": "CHF",
    "AUS DOLLAR": "AUD", "AUD": "AUD",
    "CANADIAN DOLLAR": "CAD", "CAD": "CAD",
    "SGD": "SGD",
}
CURR_MAP = CURRENCY_MAP  # Alias for backward compatibility

PAYMENT_TERMS_MAP: Dict[str, str] = {
    "NET30": "NET 30", "NET 30": "NET 30", "30 DAYS": "NET 30", "30DAYS": "NET 30",
    "NET45": "NET 45", "NET 45": "NET 45", "45 DAYS": "NET 45",
    "NET60": "NET 60", "NET 60": "NET 60", "60 DAYS": "NET 60",
    "NET15": "NET 15",
    "NET7": "NET 7",
    "IMMEDIATE": "IMMEDIATE", "CASH": "CASH", "COD": "COD", "DUE ON RECEIPT": "DUE ON RECEIPT",
}
PAYMENT_TERM_MAP = PAYMENT_TERMS_MAP  # Alias for backward compatibility

COUNTRY_FIELD_NAMES: Set[str] = {"COUNTRY", "COUNTRY_CODE"}
CURRENCY_FIELD_NAMES: Set[str] = {"CURRENCY", "CURRENCY_CODE", "CURR"}
PAYMENT_TERM_FIELD_NAMES: Set[str] = {"PAYMENT_TERMS", "PAY_TERMS"}

EMAIL_RE = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")
EMAIL_DOMAINS: Dict[str, str] = {
    "gmail": "gmail.com",
    "yahoo": "yahoo.com",
    "outlook": "outlook.com",
    "hotmail": "hotmail.com",
    "icloud": "icloud.com",
    "rediffmail": "rediffmail.com",
}
